Webpack
Roddoark/chillwatch pull request #2
Opened 2021-03-16 13:11 UTC by Roddoark

2021-03-17 08:41 UTC, Haitaar requested changes

2021-03-17 08:41 UTC, Haitaar commented on src/raleway/OFL.txt
> +Copyright (c) 2010, Matt McInerney (matt@pixelspread.com),
Ca peut être bien de placer les fonts dans un dossier `static` ou `public` ou `assets` etc

2021-03-17 08:41 UTC, Haitaar commented on webpack.config.js
> +    index: './src/index.js',
`src/index.js` n'existe pas, aucun fichier d'entrée et donc pas de setup react

Exemple :  
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
 
const title = 'React with Webpack and Babel';
 
ReactDOM.render(
  <div>{title}</div>,
  document.getElementById('app')
);
```

2021-03-17 08:41 UTC, Haitaar commented on server.js
> +app.listen(3000, function () {
Pourquoi ce serveur ? Hot reload ?

2021-03-17 08:41 UTC, Haitaar commented on dist/index.html
> +  </body>
Pour permettre l'init de react-dom (après ajout de `src/index.js`)
```suggestion
  <meta name="viewport" content="width=device-width, initial-scale=1"><script defer src="/index.bundle.js"></script></head>
  <body>
    <div id="app></div>
  </body>
```

2021-03-17 08:41 UTC, Haitaar commented on .gitignore
> +dist/
Il faudra versionner ce dossier

2021-03-17 12:43 UTC, Roddoark commented on src/raleway/OFL.txt
> +Copyright (c) 2010, Matt McInerney (matt@pixelspread.com),
Dossier pour les assets créés

2021-03-17 12:43 UTC, Roddoark commented on webpack.config.js
> +    index: './src/index.js',
Ajout du fichier index.js fait

2021-03-17 12:45 UTC, Roddoark commented on server.js
> +app.listen(3000, function () {
Serveur supprimé. J'avais oublié de le supprimer après avoir regardé la documentation de webpack

2021-03-17 12:46 UTC, Roddoark commented on .gitignore
> +dist/
Ajout du dossier dist/ dans le gitignore fait

2021-03-17 12:48 UTC, Roddoark commented on dist/index.html
> +  </body>
Au départ c'est ce que j'avais fait. Mais à chaque build, la div avec l'ID s'enlève.

2021-03-18 10:05 UTC, Haitaar commented on dist/index.html
> +  </body>
Essaie avec le script en fin de body. Même avec le defer ça prend pas toujours

2021-03-18 12:51 UTC, Haitaar approved these changes

2021-03-18 17:48 UTC, merged